# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9cb530f3f0622dcbabaf998190fe750e97c06528b16b3841a2865582b4291aa1d5574d023b06f0e91e141d86e6b56868ef04c35cfdf76eb642792c5adf5f657b

test:
  secret_key_base: 5c2a64ffd2ce7d91c379a0050c3b1d4963f568c172b976c2575af5ce0b377ab17327a28a329e06e353436a9a86872c238aa756fbbfbc456f07ae324e0e2b30b9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
